---
- name: Install kraken service file
  become: true
  template:
    src: 'kraken.service.j2'
    dest: '/usr/lib/systemd/system/kraken.service'
    owner: root
    group: root
    mode: 0644
  when: not kr_rpm

- name: Write the kraken runtime configuration file
  become: true
  shell:
    cmd: >
      /usr/sbin/kraken -printrc
      -id "{{ kraken_id }}"
      -ip "{{ kraken_ip }}"
      -ipapi "{{ kraken_ipapi }}"
      -log "{{ kraken_loglevel }}"
      -state "{{ kraken_state_file }}"
      > /etc/kraken/config.yaml
      && touch /etc/kraken/.ansible_config
    creates: /etc/kraken/.ansible_config

- name: Enable & start kraken service
  become: true
  systemd:
    name: kraken.service
    enabled: true
    state: started
    daemon_reload: true
