---
- name: Install vim
  become: true
  package:
    name: vim
    state: present

- name: Install tcpdump
  become: true
  package:
    name: tcpdump
    state: present

- name: Install traceroute
  become: true
  package:
    name: traceroute
    state: present

- name: Install nmap
  become: true
  package:
    name: nmap
    state: present
