// cpuburn.proto: describes the RBDImageConfig object
//
// Author: J. Lowell Wofford <lowell@lanl.gov>
//
// This software is open source software available under the BSD-3 license.
// Copyright (c) 2020, Triad National Security, LLC
// See LICENSE file for details.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.5.1
// source: rbdimage.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RBDImageConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id        string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Secret    string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Monitors  [][]byte `protobuf:"bytes,4,rep,name=monitors,proto3" json:"monitors,omitempty"`
}

func (x *RBDImageConfig) Reset() {
	*x = RBDImageConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbdimage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RBDImageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RBDImageConfig) ProtoMessage() {}

func (x *RBDImageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rbdimage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RBDImageConfig.ProtoReflect.Descriptor instead.
func (*RBDImageConfig) Descriptor() ([]byte, []int) {
	return file_rbdimage_proto_rawDescGZIP(), []int{0}
}

func (x *RBDImageConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RBDImageConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RBDImageConfig) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *RBDImageConfig) GetMonitors() [][]byte {
	if x != nil {
		return x.Monitors
	}
	return nil
}

var File_rbdimage_proto protoreflect.FileDescriptor

var file_rbdimage_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x62, 0x64, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x0e, 0x52, 0x42, 0x44, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x08, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rbdimage_proto_rawDescOnce sync.Once
	file_rbdimage_proto_rawDescData = file_rbdimage_proto_rawDesc
)

func file_rbdimage_proto_rawDescGZIP() []byte {
	file_rbdimage_proto_rawDescOnce.Do(func() {
		file_rbdimage_proto_rawDescData = protoimpl.X.CompressGZIP(file_rbdimage_proto_rawDescData)
	})
	return file_rbdimage_proto_rawDescData
}

var file_rbdimage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rbdimage_proto_goTypes = []interface{}{
	(*RBDImageConfig)(nil), // 0: proto.RBDImageConfig
}
var file_rbdimage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rbdimage_proto_init() }
func file_rbdimage_proto_init() {
	if File_rbdimage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rbdimage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RBDImageConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rbdimage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rbdimage_proto_goTypes,
		DependencyIndexes: file_rbdimage_proto_depIdxs,
		MessageInfos:      file_rbdimage_proto_msgTypes,
	}.Build()
	File_rbdimage_proto = out.File
	file_rbdimage_proto_rawDesc = nil
	file_rbdimage_proto_goTypes = nil
	file_rbdimage_proto_depIdxs = nil
}
